using DG.Tweening;
using UnityEngine;
using UnityEngine.UI;

public class WolfEyeController : MonoBehaviour
{
    [SerializeField] private float timer;
    public AudioClip voiceSE;
    AudioSource audioSource;
    void Start()
    {
        // ƒXƒPپ[ƒ‹‚ً0‚©‚ç100‚ة•د‰»‚³‚¹‚éƒAƒjƒپپ[ƒVƒ‡ƒ“‚ًٹJژn
        transform.localScale = Vector3.zero;
        transform.DOScale(new Vector3(10f, 10f, 10f), 1f); // 1•b‚إƒXƒPپ[ƒ‹•دچX
        this.audioSource = GetComponent<AudioSource>();
    }

    private void Update()
    {
        timer += Time.deltaTime;

        if (timer > 3)
        {
            timer = 0;
            this.audioSource.PlayOneShot(this.voiceSE);
            // 1•b‚©‚¯‚ؤƒXƒPپ[ƒ‹‚ً0‚ة‚µپAƒCپ[ƒWƒ“ƒO‚ً’ا‰ء
            transform.DOScale(Vector3.zero, 1f).SetEase(Ease.OutQuad).OnKill(() => Destroy(gameObject)); ;
            
        }

    }

}
